repositories:
  - name: jetstack 
    url: https://charts.jetstack.io

releases:
  - name: trust-manager
    chart: jetstack/trust-manager
    version: 0.12.0
    namespace: cert-manager
    createNamespace: true
    values:
      - ../values/trust-manager.yaml
