hydra:
  automigration:
    enabled: true
  config: 
    urls:
      self:
        issuer: https://auth.metachad.mooo.com
      login: https://auth.metachad.mooo.com/login
      consent: https://auth.metachad.mooo.com/consent
maester:
  enabled: false
deployment:
  extraEnv:
    - name: DSN
      value: postgres://hydra:change-this-3@auth-postgres.default:5432/hydra
