# Dev convenience
configure:
	cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="./build/Release/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="." -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" -S "." -B "./build/Release"
