{{- $name := "onboarding-frontend" }}
{{- with $.Values.onboarding.frontend }}
{{- if .bypass.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  type: ExternalName
  externalName: {{ .bypass.externalName }}
  ports:
   - port: 80
     targetPort: {{ .bypass.localPort }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
spec:
  selector:
    app: {{ $name }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: {{ .image }}
        ports:
        - containerPort: 80
{{- end }}
{{- end }}
