/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExerciseRef
 */
export interface ExerciseRef {
    /**
     * 
     * @type {string}
     * @memberof ExerciseRef
     */
    id: string;
}

/**
 * Check if a given object implements the ExerciseRef interface.
 */
export function instanceOfExerciseRef(value: object): value is ExerciseRef {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ExerciseRefFromJSON(json: any): ExerciseRef {
    return ExerciseRefFromJSONTyped(json, false);
}

export function ExerciseRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseRef {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function ExerciseRefToJSON(json: any): ExerciseRef {
    return ExerciseRefToJSONTyped(json, false);
}

export function ExerciseRefToJSONTyped(value?: ExerciseRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

