/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Exercise } from './Exercise';
import {
    ExerciseFromJSON,
    ExerciseFromJSONTyped,
    ExerciseToJSON,
    ExerciseToJSONTyped,
} from './Exercise';

/**
 * 
 * @export
 * @interface ExerciseLogBody
 */
export interface ExerciseLogBody {
    /**
     * 
     * @type {Exercise}
     * @memberof ExerciseLogBody
     */
    exercise: Exercise;
    /**
     * 
     * @type {number}
     * @memberof ExerciseLogBody
     */
    reps: number;
    /**
     * 
     * @type {number}
     * @memberof ExerciseLogBody
     */
    weight: number;
    /**
     * 
     * @type {number}
     * @memberof ExerciseLogBody
     */
    startedAt: number;
    /**
     * 
     * @type {number}
     * @memberof ExerciseLogBody
     */
    endedAt: number;
}

/**
 * Check if a given object implements the ExerciseLogBody interface.
 */
export function instanceOfExerciseLogBody(value: object): value is ExerciseLogBody {
    if (!('exercise' in value) || value['exercise'] === undefined) return false;
    if (!('reps' in value) || value['reps'] === undefined) return false;
    if (!('weight' in value) || value['weight'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('endedAt' in value) || value['endedAt'] === undefined) return false;
    return true;
}

export function ExerciseLogBodyFromJSON(json: any): ExerciseLogBody {
    return ExerciseLogBodyFromJSONTyped(json, false);
}

export function ExerciseLogBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseLogBody {
    if (json == null) {
        return json;
    }
    return {
        
        'exercise': ExerciseFromJSON(json['exercise']),
        'reps': json['reps'],
        'weight': json['weight'],
        'startedAt': json['startedAt'],
        'endedAt': json['endedAt'],
    };
}

export function ExerciseLogBodyToJSON(json: any): ExerciseLogBody {
    return ExerciseLogBodyToJSONTyped(json, false);
}

export function ExerciseLogBodyToJSONTyped(value?: ExerciseLogBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exercise': ExerciseToJSON(value['exercise']),
        'reps': value['reps'],
        'weight': value['weight'],
        'startedAt': value['startedAt'],
        'endedAt': value['endedAt'],
    };
}

