/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExerciseLogRef
 */
export interface ExerciseLogRef {
    /**
     * 
     * @type {string}
     * @memberof ExerciseLogRef
     */
    id: string;
}

/**
 * Check if a given object implements the ExerciseLogRef interface.
 */
export function instanceOfExerciseLogRef(value: object): value is ExerciseLogRef {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ExerciseLogRefFromJSON(json: any): ExerciseLogRef {
    return ExerciseLogRefFromJSONTyped(json, false);
}

export function ExerciseLogRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseLogRef {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function ExerciseLogRefToJSON(json: any): ExerciseLogRef {
    return ExerciseLogRefToJSONTyped(json, false);
}

export function ExerciseLogRefToJSONTyped(value?: ExerciseLogRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

