/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetConfigResponseOAuth2 } from './GetConfigResponseOAuth2';
import {
    GetConfigResponseOAuth2FromJSON,
    GetConfigResponseOAuth2FromJSONTyped,
    GetConfigResponseOAuth2ToJSON,
    GetConfigResponseOAuth2ToJSONTyped,
} from './GetConfigResponseOAuth2';

/**
 * 
 * @export
 * @interface GetConfigResponse
 */
export interface GetConfigResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {GetConfigResponseOAuth2}
     * @memberof GetConfigResponse
     */
    oAuth2: GetConfigResponseOAuth2;
}

/**
 * Check if a given object implements the GetConfigResponse interface.
 */
export function instanceOfGetConfigResponse(value: object): value is GetConfigResponse {
    if (!('oAuth2' in value) || value['oAuth2'] === undefined) return false;
    return true;
}

export function GetConfigResponseFromJSON(json: any): GetConfigResponse {
    return GetConfigResponseFromJSONTyped(json, false);
}

export function GetConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'oAuth2': GetConfigResponseOAuth2FromJSON(json['oAuth2']),
    };
}

export function GetConfigResponseToJSON(json: any): GetConfigResponse {
    return GetConfigResponseToJSONTyped(json, false);
}

export function GetConfigResponseToJSONTyped(value?: GetConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'oAuth2': GetConfigResponseOAuth2ToJSON(value['oAuth2']),
    };
}

