/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetConfigResponseOAuth2
 */
export interface GetConfigResponseOAuth2 {
    /**
     * 
     * @type {string}
     * @memberof GetConfigResponseOAuth2
     */
    authUrl: string;
    /**
     * 
     * @type {string}
     * @memberof GetConfigResponseOAuth2
     */
    tokenUrl: string;
    /**
     * 
     * @type {string}
     * @memberof GetConfigResponseOAuth2
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof GetConfigResponseOAuth2
     */
    redirectUri: string;
}

/**
 * Check if a given object implements the GetConfigResponseOAuth2 interface.
 */
export function instanceOfGetConfigResponseOAuth2(value: object): value is GetConfigResponseOAuth2 {
    if (!('authUrl' in value) || value['authUrl'] === undefined) return false;
    if (!('tokenUrl' in value) || value['tokenUrl'] === undefined) return false;
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('redirectUri' in value) || value['redirectUri'] === undefined) return false;
    return true;
}

export function GetConfigResponseOAuth2FromJSON(json: any): GetConfigResponseOAuth2 {
    return GetConfigResponseOAuth2FromJSONTyped(json, false);
}

export function GetConfigResponseOAuth2FromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConfigResponseOAuth2 {
    if (json == null) {
        return json;
    }
    return {
        
        'authUrl': json['authUrl'],
        'tokenUrl': json['tokenUrl'],
        'clientId': json['clientId'],
        'redirectUri': json['redirectUri'],
    };
}

export function GetConfigResponseOAuth2ToJSON(json: any): GetConfigResponseOAuth2 {
    return GetConfigResponseOAuth2ToJSONTyped(json, false);
}

export function GetConfigResponseOAuth2ToJSONTyped(value?: GetConfigResponseOAuth2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authUrl': value['authUrl'],
        'tokenUrl': value['tokenUrl'],
        'clientId': value['clientId'],
        'redirectUri': value['redirectUri'],
    };
}

