/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostWorkoutRequest
 */
export interface PostWorkoutRequest {
    /**
     * 
     * @type {string}
     * @memberof PostWorkoutRequest
     */
    name: string;
}

/**
 * Check if a given object implements the PostWorkoutRequest interface.
 */
export function instanceOfPostWorkoutRequest(value: object): value is PostWorkoutRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PostWorkoutRequestFromJSON(json: any): PostWorkoutRequest {
    return PostWorkoutRequestFromJSONTyped(json, false);
}

export function PostWorkoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostWorkoutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function PostWorkoutRequestToJSON(json: any): PostWorkoutRequest {
    return PostWorkoutRequestToJSONTyped(json, false);
}

export function PostWorkoutRequestToJSONTyped(value?: PostWorkoutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

