/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkoutExercise } from './WorkoutExercise';
import {
    WorkoutExerciseFromJSON,
    WorkoutExerciseFromJSONTyped,
    WorkoutExerciseToJSON,
    WorkoutExerciseToJSONTyped,
} from './WorkoutExercise';

/**
 * 
 * @export
 * @interface PutWorkoutRequest
 */
export interface PutWorkoutRequest {
    /**
     * 
     * @type {string}
     * @memberof PutWorkoutRequest
     */
    name?: string;
    /**
     * 
     * @type {Array<WorkoutExercise>}
     * @memberof PutWorkoutRequest
     */
    exercises?: Array<WorkoutExercise>;
}

/**
 * Check if a given object implements the PutWorkoutRequest interface.
 */
export function instanceOfPutWorkoutRequest(value: object): value is PutWorkoutRequest {
    return true;
}

export function PutWorkoutRequestFromJSON(json: any): PutWorkoutRequest {
    return PutWorkoutRequestFromJSONTyped(json, false);
}

export function PutWorkoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutWorkoutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'exercises': json['exercises'] == null ? undefined : ((json['exercises'] as Array<any>).map(WorkoutExerciseFromJSON)),
    };
}

export function PutWorkoutRequestToJSON(json: any): PutWorkoutRequest {
    return PutWorkoutRequestToJSONTyped(json, false);
}

export function PutWorkoutRequestToJSONTyped(value?: PutWorkoutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'exercises': value['exercises'] == null ? undefined : ((value['exercises'] as Array<any>).map(WorkoutExerciseToJSON)),
    };
}

