/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MuscleGroup } from './MuscleGroup';
import {
    MuscleGroupFromJSON,
    MuscleGroupFromJSONTyped,
    MuscleGroupToJSON,
    MuscleGroupToJSONTyped,
} from './MuscleGroup';

/**
 * 
 * @export
 * @interface WorkoutHeader
 */
export interface WorkoutHeader {
    /**
     * 
     * @type {string}
     * @memberof WorkoutHeader
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof WorkoutHeader
     */
    editedAt: number;
    /**
     * 
     * @type {Array<MuscleGroup>}
     * @memberof WorkoutHeader
     */
    muscleGroups: Array<MuscleGroup>;
}

/**
 * Check if a given object implements the WorkoutHeader interface.
 */
export function instanceOfWorkoutHeader(value: object): value is WorkoutHeader {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('editedAt' in value) || value['editedAt'] === undefined) return false;
    if (!('muscleGroups' in value) || value['muscleGroups'] === undefined) return false;
    return true;
}

export function WorkoutHeaderFromJSON(json: any): WorkoutHeader {
    return WorkoutHeaderFromJSONTyped(json, false);
}

export function WorkoutHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkoutHeader {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'editedAt': json['editedAt'],
        'muscleGroups': ((json['muscleGroups'] as Array<any>).map(MuscleGroupFromJSON)),
    };
}

export function WorkoutHeaderToJSON(json: any): WorkoutHeader {
    return WorkoutHeaderToJSONTyped(json, false);
}

export function WorkoutHeaderToJSONTyped(value?: WorkoutHeader | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'editedAt': value['editedAt'],
        'muscleGroups': ((value['muscleGroups'] as Array<any>).map(MuscleGroupToJSON)),
    };
}

