/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkoutExercise } from './WorkoutExercise';
import {
    WorkoutExerciseFromJSON,
    WorkoutExerciseFromJSONTyped,
    WorkoutExerciseToJSON,
    WorkoutExerciseToJSONTyped,
} from './WorkoutExercise';

/**
 * 
 * @export
 * @interface WorkoutBody
 */
export interface WorkoutBody {
    /**
     * 
     * @type {Array<WorkoutExercise>}
     * @memberof WorkoutBody
     */
    exercises: Array<WorkoutExercise>;
}

/**
 * Check if a given object implements the WorkoutBody interface.
 */
export function instanceOfWorkoutBody(value: object): value is WorkoutBody {
    if (!('exercises' in value) || value['exercises'] === undefined) return false;
    return true;
}

export function WorkoutBodyFromJSON(json: any): WorkoutBody {
    return WorkoutBodyFromJSONTyped(json, false);
}

export function WorkoutBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkoutBody {
    if (json == null) {
        return json;
    }
    return {
        
        'exercises': ((json['exercises'] as Array<any>).map(WorkoutExerciseFromJSON)),
    };
}

export function WorkoutBodyToJSON(json: any): WorkoutBody {
    return WorkoutBodyToJSONTyped(json, false);
}

export function WorkoutBodyToJSONTyped(value?: WorkoutBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exercises': ((value['exercises'] as Array<any>).map(WorkoutExerciseToJSON)),
    };
}

