/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkoutRef
 */
export interface WorkoutRef {
    /**
     * 
     * @type {string}
     * @memberof WorkoutRef
     */
    id: string;
}

/**
 * Check if a given object implements the WorkoutRef interface.
 */
export function instanceOfWorkoutRef(value: object): value is WorkoutRef {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function WorkoutRefFromJSON(json: any): WorkoutRef {
    return WorkoutRefFromJSONTyped(json, false);
}

export function WorkoutRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkoutRef {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function WorkoutRefToJSON(json: any): WorkoutRef {
    return WorkoutRefToJSONTyped(json, false);
}

export function WorkoutRefToJSONTyped(value?: WorkoutRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

