/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkoutRef } from './WorkoutRef';
import {
    WorkoutRefFromJSON,
    WorkoutRefFromJSONTyped,
    WorkoutRefToJSON,
    WorkoutRefToJSONTyped,
} from './WorkoutRef';
import type { MuscleGroup } from './MuscleGroup';
import {
    MuscleGroupFromJSON,
    MuscleGroupFromJSONTyped,
    MuscleGroupToJSON,
    MuscleGroupToJSONTyped,
} from './MuscleGroup';

/**
 * 
 * @export
 * @interface WorkoutLogDescription
 */
export interface WorkoutLogDescription {
    /**
     * 
     * @type {string}
     * @memberof WorkoutLogDescription
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WorkoutLogDescription
     */
    name: string;
    /**
     * 
     * @type {WorkoutRef}
     * @memberof WorkoutLogDescription
     */
    baseWorkoutRef: WorkoutRef;
    /**
     * 
     * @type {number}
     * @memberof WorkoutLogDescription
     */
    startedAt: number;
    /**
     * 
     * @type {number}
     * @memberof WorkoutLogDescription
     */
    endedAt: number;
    /**
     * 
     * @type {Array<MuscleGroup>}
     * @memberof WorkoutLogDescription
     */
    muscleGroups: Array<MuscleGroup>;
}

/**
 * Check if a given object implements the WorkoutLogDescription interface.
 */
export function instanceOfWorkoutLogDescription(value: object): value is WorkoutLogDescription {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('baseWorkoutRef' in value) || value['baseWorkoutRef'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('endedAt' in value) || value['endedAt'] === undefined) return false;
    if (!('muscleGroups' in value) || value['muscleGroups'] === undefined) return false;
    return true;
}

export function WorkoutLogDescriptionFromJSON(json: any): WorkoutLogDescription {
    return WorkoutLogDescriptionFromJSONTyped(json, false);
}

export function WorkoutLogDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkoutLogDescription {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'baseWorkoutRef': WorkoutRefFromJSON(json['baseWorkoutRef']),
        'startedAt': json['startedAt'],
        'endedAt': json['endedAt'],
        'muscleGroups': ((json['muscleGroups'] as Array<any>).map(MuscleGroupFromJSON)),
    };
}

export function WorkoutLogDescriptionToJSON(json: any): WorkoutLogDescription {
    return WorkoutLogDescriptionToJSONTyped(json, false);
}

export function WorkoutLogDescriptionToJSONTyped(value?: WorkoutLogDescription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'baseWorkoutRef': WorkoutRefToJSON(value['baseWorkoutRef']),
        'startedAt': value['startedAt'],
        'endedAt': value['endedAt'],
        'muscleGroups': ((value['muscleGroups'] as Array<any>).map(MuscleGroupToJSON)),
    };
}

