/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExerciseLog } from './ExerciseLog';
import {
    ExerciseLogFromJSON,
    ExerciseLogFromJSONTyped,
    ExerciseLogToJSON,
    ExerciseLogToJSONTyped,
} from './ExerciseLog';

/**
 * 
 * @export
 * @interface WorkoutLogBody
 */
export interface WorkoutLogBody {
    /**
     * 
     * @type {Array<ExerciseLog>}
     * @memberof WorkoutLogBody
     */
    exercises: Array<ExerciseLog>;
}

/**
 * Check if a given object implements the WorkoutLogBody interface.
 */
export function instanceOfWorkoutLogBody(value: object): value is WorkoutLogBody {
    if (!('exercises' in value) || value['exercises'] === undefined) return false;
    return true;
}

export function WorkoutLogBodyFromJSON(json: any): WorkoutLogBody {
    return WorkoutLogBodyFromJSONTyped(json, false);
}

export function WorkoutLogBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkoutLogBody {
    if (json == null) {
        return json;
    }
    return {
        
        'exercises': ((json['exercises'] as Array<any>).map(ExerciseLogFromJSON)),
    };
}

export function WorkoutLogBodyToJSON(json: any): WorkoutLogBody {
    return WorkoutLogBodyToJSONTyped(json, false);
}

export function WorkoutLogBodyToJSONTyped(value?: WorkoutLogBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exercises': ((value['exercises'] as Array<any>).map(ExerciseLogToJSON)),
    };
}

