/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkoutExerciseRef
 */
export interface WorkoutExerciseRef {
    /**
     * 
     * @type {string}
     * @memberof WorkoutExerciseRef
     */
    id: string;
}

/**
 * Check if a given object implements the WorkoutExerciseRef interface.
 */
export function instanceOfWorkoutExerciseRef(value: object): value is WorkoutExerciseRef {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function WorkoutExerciseRefFromJSON(json: any): WorkoutExerciseRef {
    return WorkoutExerciseRefFromJSONTyped(json, false);
}

export function WorkoutExerciseRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkoutExerciseRef {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function WorkoutExerciseRefToJSON(json: any): WorkoutExerciseRef {
    return WorkoutExerciseRefToJSONTyped(json, false);
}

export function WorkoutExerciseRefToJSONTyped(value?: WorkoutExerciseRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

