/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Exercise } from './Exercise';
import {
    ExerciseFromJSON,
    ExerciseFromJSONTyped,
    ExerciseToJSON,
    ExerciseToJSONTyped,
} from './Exercise';

/**
 * 
 * @export
 * @interface WorkoutExerciseBody
 */
export interface WorkoutExerciseBody {
    /**
     * 
     * @type {Exercise}
     * @memberof WorkoutExerciseBody
     */
    exercise: Exercise;
    /**
     * 
     * @type {number}
     * @memberof WorkoutExerciseBody
     */
    sets: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof WorkoutExerciseBody
     */
    repRange: Array<number>;
}

/**
 * Check if a given object implements the WorkoutExerciseBody interface.
 */
export function instanceOfWorkoutExerciseBody(value: object): value is WorkoutExerciseBody {
    if (!('exercise' in value) || value['exercise'] === undefined) return false;
    if (!('sets' in value) || value['sets'] === undefined) return false;
    if (!('repRange' in value) || value['repRange'] === undefined) return false;
    return true;
}

export function WorkoutExerciseBodyFromJSON(json: any): WorkoutExerciseBody {
    return WorkoutExerciseBodyFromJSONTyped(json, false);
}

export function WorkoutExerciseBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkoutExerciseBody {
    if (json == null) {
        return json;
    }
    return {
        
        'exercise': ExerciseFromJSON(json['exercise']),
        'sets': json['sets'],
        'repRange': json['repRange'],
    };
}

export function WorkoutExerciseBodyToJSON(json: any): WorkoutExerciseBody {
    return WorkoutExerciseBodyToJSONTyped(json, false);
}

export function WorkoutExerciseBodyToJSONTyped(value?: WorkoutExerciseBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exercise': ExerciseToJSON(value['exercise']),
        'sets': value['sets'],
        'repRange': value['repRange'],
    };
}

