/* tslint:disable */
/* eslint-disable */
/**
 * Training service
 * Backend for training app
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkoutRef } from './WorkoutRef';
import {
    WorkoutRefFromJSON,
    WorkoutRefFromJSONTyped,
    WorkoutRefToJSON,
    WorkoutRefToJSONTyped,
} from './WorkoutRef';
import type { MuscleGroup } from './MuscleGroup';
import {
    MuscleGroupFromJSON,
    MuscleGroupFromJSONTyped,
    MuscleGroupToJSON,
    MuscleGroupToJSONTyped,
} from './MuscleGroup';

/**
 * 
 * @export
 * @interface WorkoutLogHeader
 */
export interface WorkoutLogHeader {
    /**
     * 
     * @type {string}
     * @memberof WorkoutLogHeader
     */
    name: string;
    /**
     * 
     * @type {WorkoutRef}
     * @memberof WorkoutLogHeader
     */
    baseWorkoutRef: WorkoutRef;
    /**
     * 
     * @type {number}
     * @memberof WorkoutLogHeader
     */
    startedAt: number;
    /**
     * 
     * @type {number}
     * @memberof WorkoutLogHeader
     */
    endedAt: number;
    /**
     * 
     * @type {Array<MuscleGroup>}
     * @memberof WorkoutLogHeader
     */
    muscleGroups: Array<MuscleGroup>;
}

/**
 * Check if a given object implements the WorkoutLogHeader interface.
 */
export function instanceOfWorkoutLogHeader(value: object): value is WorkoutLogHeader {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('baseWorkoutRef' in value) || value['baseWorkoutRef'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('endedAt' in value) || value['endedAt'] === undefined) return false;
    if (!('muscleGroups' in value) || value['muscleGroups'] === undefined) return false;
    return true;
}

export function WorkoutLogHeaderFromJSON(json: any): WorkoutLogHeader {
    return WorkoutLogHeaderFromJSONTyped(json, false);
}

export function WorkoutLogHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkoutLogHeader {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'baseWorkoutRef': WorkoutRefFromJSON(json['baseWorkoutRef']),
        'startedAt': json['startedAt'],
        'endedAt': json['endedAt'],
        'muscleGroups': ((json['muscleGroups'] as Array<any>).map(MuscleGroupFromJSON)),
    };
}

export function WorkoutLogHeaderToJSON(json: any): WorkoutLogHeader {
    return WorkoutLogHeaderToJSONTyped(json, false);
}

export function WorkoutLogHeaderToJSONTyped(value?: WorkoutLogHeader | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'baseWorkoutRef': WorkoutRefToJSON(value['baseWorkoutRef']),
        'startedAt': value['startedAt'],
        'endedAt': value['endedAt'],
        'muscleGroups': ((value['muscleGroups'] as Array<any>).map(MuscleGroupToJSON)),
    };
}

